### ISSUE TITLE
Indicate duplicate records

### ISSUE THREAD

**Issue by bernhard-r-schubert** [gabriele-h/bib-hierarchy#4]
Duplicate dependent records in hierarchies would ideally be indicated (e.g. by colour) so it's immediately clear that they should be corrected. Duplicates are marked with string "dublette" (not case-sensitive) in 970 0#.

**Comment by gabriele-h** [comment]
Resolved in fc1797ffa2c3d8395f4079d24fb47256fd01c3e7
